title: Simon's Blog
description: Research, hobbies, and more
theme: jekyll-theme-cayman            # GitHub's default theme, or pick another
navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Hobbies
    url: /hobbies/
